FROM amazonlinux:2

# DO NOT yum update (causes your error)
RUN yum install -y unzip curl \
 && yum clean all

# Install AWS CLI v2
RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip \
 && unzip awscliv2.zip \
 && ./aws/install \
 && rm -rf aws awscliv2.zip

CMD ["aws", "--version"]
# Verify installation (optional, you can remove this in your final Dockerfile)
RUN aws --version