FROM amazon/aws-cli
RUN yum install -y tar ca-certificates && yum clean all

# Install Docker CLI only
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-26.1.3.tgz \
  | tar -xz --strip-components=1 -C /usr/local/bin docker/docker

RUN docker --version && aws --version