FROM amazonlinux:2
# Install necessary dependencies (unzip and curl)
RUN yum update -y && yum install -y unzip curl

# Install AWS CLI v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

# Verify installation (optional, you can remove this in your final Dockerfile)
RUN aws --version
RUN amazon-linux-extras install docker